[run]
build_delay = 1500 # Minimal interval to Trigger build event
cmds = [
  # Commands to run
  ["go", "install", "-race"],
] 
env_files = [] # Load env vars from files 
follow_symlinks = false # Enable/disable following symbolic links of sub directories
graceful_kill = false # Wait for exit and before directly kill
ignore = [".git", "node_modules"] # Directories to exclude from watching 
ignore_files = [] # Regexps for ignoring specific notifies 
init_cmds = [
  # Commands run in start
  ["go", "install", "-race"],
] 
interrupt_timout = 15 # Time to wait until force kill
watch_all = true # Watch all sub-directories
watch_dirs = [] # Directories to watch 
watch_exts = [".go"] # Extensions to watch 

[sync]
listen_addr = ":5050"
remote_addr = ":5050"
